- name: "Get go-asdf location"
  command: "~/.asdf/bin/asdf which go"
  register: go_location
  check_mode: no
  changed_when: false


- name: "Install Go Packages"
  command: "{{ go_location.stdout }} get -u {{ item }}"
  with_items: "{{ default_packages }}"
  changed_when: false
