- name: "VsCode"
  snap:
    name: code-insiders
    classic: yes
  become: true

- name: "Install emacs ppa"
  apt_repository:
    repo: ppa:ubuntu-elisp/ppa
  become: True

- name: "Install emacs ppa"
  apt_repository:
    repo: ppa:kelleyk/emacs
  become: True

- name: "Install emacs"
  apt:
    name:
      - emacs26
    update_cache: True
  become: True

- name: "emacs doom git repository"
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
  register: emacs_doom

- name: "Stat doom folder"
  stat:
    path: ~/.doom.d
  register: doom_path

- name: "Install doom if folder not exists"
  command: ~/.emacs.d/bin/doom --yes install
  when: not p.stat.exists
