- name: "Ensure folder exists"
  file:
    state: directory 
    dest: "~/.local/bin"

- name: "Symlink Devsible shortcut"
  file:
    src: "{{ playbook_dir }}/files/devsible.py"
    dest: "~/.local/bin/devsible"
    state: link
