- name: "Get Kanshi"
  git:
    repo: "https://github.com/emersion/kanshi.git"
    dest: "{{ kanshi_directory }}"
  tags:
    - kanshi
  notify:
    - kanshi-changed
  when: ansible_distribution == "Ubuntu"

- aur:
    name: kanshi-git
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
