- name: "Install blueman"
  apt:
    name:
      - blueman
      - bluez-tools
  when: ansible_distribution == "Ubuntu"
  become: True

- name: "Install blueman"
  community.general.pacman:
    name:
      - blueman
      - bluez-tools
      - bluez-utils
  when: ansible_distribution == "Archlinux"
  tags: bluetooth
  become: True

- name: "Make sure bluetooth is enabled and started"
  systemd:
    name: bluetooth.service
    state: started
    enabled: True
  when: ansible_distribution == "Archlinux"
  tags: bluetooth
  become: True

- name: "Copy over bluetooth configuration"
  copy:
    src: files/main.conf
    dest: /etc/bluetooth/main.conf
  when: ansible_distribution == "Archlinux"
  notify: bluetooth-restart
  tags: bluetooth
  become: True
