- name: "WAYLAND - meson build"
  command: meson build/ --prefix=/usr
  args:
    chdir: "{{ wayland_path }}"
  listen: "wayland-changed"

- name: "WAYLAND - ninja build"
  command: ninja -C build/ install
  args:
    chdir: "{{ wayland_path | expanduser }}"
  listen: "wayland-changed"
  become: True

- name: "WLROOTS - meson build"
  command: meson build -Dauto_features=enabled -Dlogind-provider=systemd -Dxwayland=enabled -Dxcb-errors=disabled -Dlibseat=disabled
  args:
    chdir: "{{ wlroots_path }}"
  listen:
    - wlroots-changed
    - wayland-changed

- name: "WLROOTS - ninja build"
  command: ninja -C build
  args:
    chdir: "{{ wlroots_path }}"
  listen:
    - wlroots-changed
    - wayland-changed

- name: "WLROOTS - ninja install"
  command: ninja -C build install
  args:
    chdir: "{{ wlroots_path | expanduser}}"
  listen:
    - wlroots-changed
    - wayland-changed
  become: True

- name: "SWAY - meson build"
  command: meson build -Dxwayland=enabled
  args:
    chdir: "{{ sway_path }}"
  listen:
    - sway-changed
    - wlroots-changed
    - wayland-changed

- name: "SWAY - ninja build"
  command: ninja -C build
  args:
    chdir: "{{ sway_path }}"
  listen:
    - sway-changed
    - wlroots-changed
    - wayland-changed

- name: "SWAY - ninja install"
  command: ninja -C build install
  args:
    chdir: "{{ sway_path | expanduser }}"
  become: True
  listen:
    - sway-changed
    - wlroots-changed
    - wayland-changed

- name: "WAYBAR - meson build"
  command: meson build/ --prefix=/usr
  args:
    chdir: "{{ waybar_path }}"
  listen: "waybar-changed"

- name: "WAYBAR - ninja build"
  command: ninja -C build/ install
  args:
    chdir: "{{ waybar_path | expanduser }}"
  listen: "waybar-changed"
  become: True

- name: "SWAYIDLE - meson build"
  command: meson build/ --prefix=/usr
  args:
    chdir: "{{ swayidle_path }}"
  listen: "swayidle-changed"

- name: "SWAYIDLE - ninja build"
  command: ninja -C build/ install
  args:
    chdir: "{{ swayidle_path | expanduser }}"
  listen: "swayidle-changed"
  become: True

- name: "SWAYLOCK - meson build"
  command: meson build/ --prefix=/usr
  args:
    chdir: "{{ swaylock_path }}"
  listen: "swaylock-changed"

- name: "SWAYLOCK - ninja build"
  command: ninja -C build/ install
  args:
    chdir: "{{ swaylock_path | expanduser }}"
  listen: "swaylock-changed"
  become: True
