- name: "Get latest python 3"
  apt:
    name:
      - python3
      - python2.7
      - python-pip
      - python3-pip
    state: latest
  become: true
  tags:
    - python

- name: "Ensure other deps are made available"
  pip:
    executable: pip3
    name:
      - pipenv
      - psutil
      - emoji
      - pulsectl
      - cookiecutter
      - ninja
      - meson
    state: latest
  tags:
    - python

- name: "Lazy way to ensure that I can compile stuff on root"
  pip:
    executable: pip3
    name:
      - ninja
      - meson
    state: latest
  become: True
  tags:
    - python
