- name: "Get latest python 3"
  apt:
    name:
      - python3
      - python2.7
      - python-pip
      - python3-pip
    state: latest
  become: true

- name: "Ensure other deps are made available"
  pip:
    executable: pip3
    name:
      - pipenv
      - psutil
      - emoji
      - pulsectl
      - cookiecutter
