- name: ensure directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: ensure file exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh/environment"
    state: touch
