
- name: "Get latest asdf"
  tags:
    - asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    update: false
  register: asdf_git_pre

- name: "Update asdf to latest"
  tags:
    - asdf
  command: ~/.asdf/bin/asdf update
  changed_when: false

- name: "Create completions folder"
  file:
    path: ~/.config/fish/completions/asdf.fish
    state: directory

- name: "Get completions"
  tags:
    - asdf
  copy:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish

- name: "Did asdf update?"
  tags:
    - asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    update: false
  register: asdf_git_post
  changed_when: "asdf_git_pre.before != asdf_git_post.before"

- name: "Install asdf plugins"
  command: "asdf plugin add {{ item.name }}"
  with_items: "{{ packages }}"
  register: asdf_plugin
  changed_when: "'already added' not in asdf_plugin.stdout"

- name: "Install asdf packages"
  command: "asdf install {{ item.name }} {{ item.version }}"
  with_items: "{{ packages }}"
  register: asdf_plugin
  changed_when: "'already installed' not in asdf_plugin.stdout"

- name: "Force reshim after plugins"
  command: "asdf reshim"
  changed_when: False