
- name: "Get latest asdf"
  tags:
    - asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    update: false
  register: asdf_git_pre

- name: "Update asdf to latest"
  tags:
    - asdf
  command: ~/.asdf/bin/asdf update
  changed_when: false

- name: "Create completions folder"
  file:
    path: ~/.config/fish/completions
    state: directory

- name: "Get completions"
  tags:
    - asdf
  copy:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish

- name: "asdf state"
  tags:
    - asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    update: false
  register: asdf_git_post
  changed_when: "asdf_git_pre.before != asdf_git_post.before"

- name: "Install asdf plugins"
  command: "~/.asdf/bin/asdf plugin-add {{ item.name }}"
  with_items: "{{ asdf_packages }}"
  register: asdf_plugin
  failed_when: "asdf_plugin.rc not in (0, 2)"
  changed_when: "asdf_plugin.rc != 2"

- name: "Install asdf packages"
  command: "~/.asdf/bin/asdf install {{ item.name }} {{ item.version }}"
  with_items: "{{ asdf_packages }}"
  register: asdf_package
  changed_when: asdf_package.stdout is not search("already installed")

- name: "Set global versions"
  command: "~/.asdf/bin/asdf global {{ item.name }} {{ item.version }}"
  with_items: "{{ asdf_packages }}"
  changed_when: False

- name: "Force reshim after plugins"
  command: "~/.asdf/bin/asdf reshim"
  changed_when: False
