- name: "wl-clipboard does not have a good version in apt. Compile it yourself"
  git:
    repo: "https://github.com/bugaevc/wl-clipboard.git"
    dest: "{{ wl_clipboard_directory }}"
  notify: wl-clipboard-changed
  tags:
    - wl-clipboard
