- name: "Install Lutris ppa"
  apt_repository:
    repo: ppa:lutris-team/lutris
  become: True

- name: "Install lutris"
  apt:
    name: lutris
    update_cache: true
  become: True

- name: "Install Wine Key"
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
  become: True

- name: "Install Wine Repository"
  apt_repository:
    repo: "deb https://dl.winehq.org/wine-builds/ubuntu/ eoan main"
  become: True

- name: "Install wine and dependencies"
  apt:
    name:
      - winehq-stable
      - wine-stable
      - wine-stable-i386
      - wine-stable-amd64
      - libgnutls30:i386
      - libldap-2.4-2:i386
      - libgpg-error0:i386
      - libxml2:i386
      - libasound2-plugins:i386
      - libsdl2-2.0-0:i386
      - libfreetype6:i386
      - libdbus-1-3:i386
      - libsqlite3-0:i386
    install_recommends: True
    update_cache: True
  become: True
