asdf_git_info:
  before: HEAD

asdf_packages:
  - name: 1password
    version: 0.9.2
  - name: kubectl
    version: 1.19.1
  - name: hub
    version: v2.14.2
  - name: minikube
    version: 1.11.0
  - name: kind
    version: 0.9.0
  - name: terraform
    version: 0.13.5
  - name: golang
    version: 1.14
  - name: gohugo
    version: extended_0.68.1
  - name: "github-cli"
    version: "0.11.1"
