- name: "Ensure neofetch is available"
  apt:
    name:
      - neofetch
      - ranger
  become: true

- name: "Install role applications"
  snap:
    name: glances
  become: true

- name: "Install utilities"
  apt:
    name:
      - curl
      - wget
      - fzf
  become: true