- name: "Tools"
  community.general.pacman:
    name:
      - neofetch
      - ranger
      - curl
      - unzip
      - wget
      - fzf
      - htop
      - x11-ssh-askpass
      - jq
      - the_silver_searcher
      - ncdu
      - ripgrep
      - xdg-utils
      - atool
      - tree
      - cloc
      - mercurial
  become: true

- name: "Ensure gpg is imported to aur"
  command: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8FD3D9A8D3800305A9FFF259D1742AD60D811D58
  become: True
  become_user: aur_builder

- name: Spotify install
  aur:
    name:
      - spotify
  become: True
  become_user: aur_builder
