- name: "Ensure neofetch is available"
  apt:
    name:
      - neofetch
      - ranger
  become: true

- name: "Install role applications"
  snap:
    name: glances
  become: true

- name: "Install utilities"
  apt:
    name:
      - curl
      - wget
      - fzf
      - htop
      - net-tools
      - wl-clipboard
      - ssh-askpass
      - jq
  become: true

- name: "install virtualbox and dependencies"
  apt:
    name:
      - virtualbox 
      - virtualbox-dkms
      - linux-headers-generic
  become: true

- name: "start virtualbox socket"
  service:
    name: virtualbox
    state: started
  become: true

- name: "Connect glances"
  command: "snap connect glances:{{item}}"
  become: true
  with_items:
    - network
    - system-observe
    - mount-observe
    - hardware-observe
    - log-observe
    - network-observe
    - physical-memory-observe
    - upower-observe
  changed_when: false