- name: "Ensure neofetch is available"
  apt:
    name:
      - neofetch
      - ranger
  become: true

- name: "Install spotify key"
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
  become: True

- name: "Install spotify repo"
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    update_cache: True
  become: True

- name: "Install spotify-client"
  apt:
    name: spotify-client
  become: True

- name: "Install utilities"
  apt:
    name:
      - curl
      - unzip
      - wget
      - fzf
      - htop
      - net-tools
      - wl-clipboard
      - ssh-askpass
      - jq
      - silversearcher-ag
      - ncdu
      - ripgrep
      - xdg-utils
      - mime-support
      - atool
      - tree
      - cloc
      - mercurial
  become: true

- name: "install virtualbox and dependencies"
  apt:
    name:
      - virtualbox 
      - virtualbox-dkms
      - linux-headers-generic
  become: true

