- name: "Install ecrypt and dependencies"
  community.general.pacman:
    name:
      - ecryptfs-utils
      - rsync
      - lsof
    become: True

- name: "Load kernel module"
  community.general.modprobe:
    name: ecryptfs
    state: Present
  become: True

- name: "Get password"
  pause:
    prompt: "Enter users password"
    echo: no
  register: user_password

- name: "Encrypt users homefolder"
  command: ecryptfs-migrate-home --user {{ ansible_user }}
  args:
    stdin: "{{ user_password.user_input }}"
    chdir: /
