- name: "Install ecrypt and dependencies"
  community.general.pacman:
    name:
      - ecryptfs-utils
      - rsync
      - lsof
  become: True

- name: "Load kernel module"
  community.general.modprobe:
    name: ecryptfs
    state: present
  become: True
  ignore_errors: True
  register: load_kernel_module

- name: stat ecryptfs
  stat:
    path: "{{ ansible_env.HOME }}/."
  register: ecrypt_folder

- block:
  - name: "Create ecryptfs module load component"
    copy:
      dest: /etc/modules-load.d/ecryptfs.conf
      content: "ecryptfs"

  - name: "Dump our own pam config if we're running in encrypted mode"
    copy:
      src: files/system-auth
      dest: /etc/pam.d/system-auth
  become: True
  when: load_kernel_module is not failed and ecrypt_folder.stat.exists and ecrypt_folder.stat.isdir
