- name: "Get wofi"
  hg:
    repo: "https://hg.sr.ht/~scoopta/wofi"
    dest: "{{ directory.path }}/wofi"
  register: wofi_repo

- name: "meson build"
  command: meson build
  args:
    chdir: "{{directory.path}}/wofi"
  when: wofi_repo.changed

- name: "ninja build"
  command: ninja -C build
  args:
    chdir: "{{directory.path}}/wofi"
  when: wofi_repo.changed

- name: "ninja build"
  command: ninja -C build install
  args:
    chdir: "{{directory.path}}/wofi"
  when: wofi_repo.changed
  become: True
