- name: "meson build"
  command: meson build
  args:
    chdir: "{{ wl_clipboard_directory }}"
  listen:
    - wl-clipboard-changed

- name: "ninja build"
  command: ninja
  args:
    chdir: "{{ wl_clipboard_directory }}/build"
  listen:
    - wl-clipboard-changed

- name: "ninja install"
  command: ninja install
  args:
    chdir: "{{ wl_clipboard_directory | expanduser}}/build"
  listen:
    - wl-clipboard-changed
  become: True
