- name: "Build kitty"
  make:
    chdir: "{{ kitty_path }}"
  listen:
    - kitty-changed

- name: "Build kitty"
  command: python3 setup.py linux-package  --update-check-interval=0
  args:
    chdir: "{{ kitty_path }}"
  listen:
    - kitty-changed
  # TODO: Always fails first compilation
  retries: 2
  register: result
  until: result.rc == 0

- name: "Copy kitty folder"
  synchronize:
    src: "{{ kitty_path | expanduser }}/linux-package/"
    dest: "/usr/local/"
    perms: yes
    recursive: yes
  become: True
  listen:
    - kitty-changed
