- name: "Build kitty"
  make:
    chdir: "{{ kitty_path }}"
  listen:
    - kitty-changed

- name: "Build kitty"
  command: python3 setup.py linux-package
  args:
    chdir: "{{ kitty_path }}"
  listen:
    - kitty-changed

- name: "Copy kitty folder"
  copy:
    src: "{{ kitty_path | expanduser }}/linux-package"
    dest: "/usr/local/"
  become: True
  listen:
    - kitty-changed

- name: "Ensure kitty is executable"
  file:
    path: "/usr/local/bin/kitty"
    state: file
    mode: "755"
  become: True
  listen:
    - kitty-changed

- name: "Ensure kitty is executable"
  file:
    path: "/usr/local/share/terminfo/x/xterm-kitty"
    state: file
    mode: "755"
  become: True
  listen:
    - kitty-changed
