- name: "Install lightdm"
  apt:
    name: lightdm
  become: true

- name: "Register where lightdm is installed"
  command: "which lightdm"
  register: lightdm_location
  changed_when: False

- name: "Set default displaymanager to lightdm"
  copy:
    content: "{{ lightdm_location.stdout }}"
    dest: /etc/X11/default-display-manager
  become: true
  register: lightdm_displaymanager

- name: Run dpkg-reconfigure lightdm
  command: dpkg-reconfigure lightdm
  environment:
    DEBCONF_NONINTERACTIVE_SEEN: "true"
    DEBIAN_FRONTEND: noninteractive
  when: lightdm_displaymanager.changed
  become: true