- name: "meson build"
  command: meson build
  args:
    chdir: "{{ wf_recorder_path }}"
  listen:
    - wf-recorder-changed

- name: "ninja build"
  command: ninja
  args:
    chdir: "{{ wf_recorder_path }}/build"
  listen:
    - wf-recorder-changed

- name: "ninja install"
  command: ninja install
  args:
    chdir: "{{ wf_recorder_path | expanduser }}/build"
  listen:
    - wf-recorder-changed
  become: True
