- aur:
    name:
      - sway-git
      - wlroots-git
      - kanshi-git
  become: True
  become_user: aur_builder

- name: "Ensure cache is updated"
  community.general.pacman:
    name:
      - waybar
      - dmenu
      - swayidle
      - mako
      - grim
      - slurp
      - swayidle
      - swaylock
  become: True
