- include_tasks:
    file: main_ubuntu.yaml
    apply:
      tags: sway
  when: ansible_distribution == "Ubuntu"
  tags: sway

- include_tasks:
    file: main_arch.yaml
    apply:
      tags: sway
  when: ansible_distribution == "Archlinux"
  tags: sway
