- name: Install basic sway and its dependencies
  apt:
    name:
      - sway
      - swaybg
      - swaylock
      - swayidle
      - libevdev-tools
      - slurp
      - grim
      - ffmpeg
      - brightnessctl
      - acpid
  become: True

- name: "Install build time dependencies"
  apt:
    name:
      - meson
      - ninja-build
      - wayland-protocols
      - libwayland-dev
  become: True

- name: "Ensure base folder is created"
  file:
    path: "~/Code/Github"
    state: "directory"
  register: directory

- name: "Get a better backlight manager"
  git:
    repo: "https://github.com/haikarainen/light"
    dest: "{{directory.path}}/light"
  register: light_repo

- name: "light - autogen.sh"
  command: ./autogen.sh
  args:
    chdir: "{{directory.path}}/light"
  when: light_repo.changed

- name: "light - configure"
  command: ./configure --with-udev
  args:
    chdir: "{{directory.path}}/light"
  when: light_repo.changed

- name: "light - make"
  make:
    chdir: "{{directory.path}}/light"
  when: light_repo.changed

- name: "light - make"
  make:
    chdir: "{{directory.path}}/light"
    target: install
  become: True
  when: light_repo.changed

- name: "Add acpid brightness controls"
  copy:
    src: "files/{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - acpi/events/bl-down
    - acpi/events/bl-up
  become: True
  register: acpid_controls

- name: "Reload acpid"
  service:
    name: acpid
    state: restarted
  become: True
  when: acpid_controls.changed

- name: "wl-clipboard does not have a good version in apt. Compile it yourself"
  git:
    repo: "https://github.com/bugaevc/wl-clipboard.git"
    dest: "{{directory.path}}/wl-clipboard"
  register: wl_clipboard_repo

- name: "meson build"
  command: meson build
  args:
    chdir: "{{directory.path}}/wl-clipboard"
  when: wl_clipboard_repo.changed

- name: "ninja build"
  command: ninja
  args:
    chdir: "{{directory.path}}/wl-clipboard/build"
  when: wl_clipboard_repo.changed

- name: "ninja install"
  command: ninja install
  args:
    chdir: "{{directory.path}}/wl-clipboard/build"
  when: wl_clipboard_repo.changed
  become: True

- name: "Get Kanshi"
  git:
    repo: "https://github.com/emersion/kanshi.git"
    dest: "{{directory.path}}/kanshi"
  register: kanshi_repo

- name: "meson build"
  command: meson build
  args:
    chdir: "{{directory.path}}/kanshi"
  when: kanshi_repo.changed

- name: "ninja build"
  command: ninja
  args:
    chdir: "{{directory.path}}/kanshi/build"
  when: kanshi_repo.changed

- name: "ninja install"
  command: ninja install
  args:
    chdir: "{{directory.path}}/kanshi/build"
  when: kanshi_repo.changed
  become: True

- name: "Install mako dependencies"
  apt:
    name:
      - libcairo2-dev
      - libcairo2
      - libgdk-pixbuf2.0-0
      - cmake
      - pkg-config
      - libsystemd-dev
  become: True

- name: "Get Mako"
  git:
    repo: "https://github.com/emersion/mako.git"
    dest: "{{directory.path}}/mako"
  register: mako_repo

- name: "meson build"
  command: meson build
  args:
    chdir: "{{directory.path}}/mako"
  when: mako_repo.changed

- name: "ninja build"
  command: ninja
  args:
    chdir: "{{directory.path}}/mako/build"
  when: mako_repo.changed

- name: "ninja install"
  command: ninja install
  args:
    chdir: "{{directory.path}}/mako/build"
  when: mako_repo.changed
  become: True
