- name: Install basic sway and its dependencies
  apt:
    name:
      - swaybg
      - swaylock
      - swayidle
      - libevdev-tools
      - autoconf
      - slurp
      - grim
      - ffmpeg
      - brightnessctl
      - libpango-1.0-0
      - acpid
      - playerctl
  become: True
  tags:
    - sway

- name: "Install build time dependencies"
  apt:
    name:
      - ninja-build
      - wayland-protocols
      - libwayland-dev
  become: True
  tags:
    - sway

- name: "Get and install wayland"
  git:
    repo: https://gitlab.freedesktop.org/wayland/wayland
    dest: "{{ wayland_path }}"
  register: wayland_repo
  notify: wayland-changed
  tags:
    - sway

- name: "Install dependency"
  apt:
    name:
      - libxml2-dev
      - graphviz
      - doxygen
      - xmlto
  become: True
  tags:
    - sway

- name: "wlroot dependencies"
  apt:
    name:
      - wayland-protocols
      - libwayland-dev
      - libegl1
      - libgles2
      - libglvnd-dev
      - libglvnd0
      - libgles2-mesa
      - libgles2-mesa-dev
      - libgbm1
      - libgbm-dev
      - libdrm2
      - libinput10
      - libinput-dev
      - libxkbcommon0
      - udev
      - libpixman-1-0
      - libcap2
      - libjson-c-dev
      - libx11-xcb-dev
      - libxcb-xinput-dev
      - libxcb-xinput0
      - libcap2
      - libcap-dev
      - libxcb-composite0
      - libxcb-composite0-dev
  become: True
  tags:
    - sway

- name: "Clone wlroots"
  git:
    repo: "https://github.com/swaywm/wlroots.git"
    dest: "{{ wlroots_path }}"
  notify: wlroots-changed
  tags:
    - sway

- name: "Clone sway"
  git:
    repo: "https://github.com/swaywm/sway.git"
    dest: "{{ sway_path }}"
  notify: sway-changed
  tags:
    - sway

- name: "Ensure session file is in place"
  copy:
    src: wayland-sessions/sway.desktop
    dest: /usr/share/wayland-sessions/sway.desktop
  become: True
  tags:
    - sway
 
- meta: flush_handlers
