- name: Install basic sway and its dependencies
  apt:
    name:
      - swaybg
      - swayidle
      - libevdev-tools
      - autoconf
      - slurp
      - grim
      - ffmpeg
      - brightnessctl
      - libpango-1.0-0
      - acpid
      - playerctl
      - gir1.2-playerctl-2.0
      - libplayerctl-dev
  become: True
  tags:
    - sway

- name: "Install build time dependencies"
  apt:
    name:
      - ninja-build
      - libdrm-dev
  become: True
  tags:
    - sway

- name: "Get and install wayland"
  git:
    repo: https://github.com/wayland-project/wayland
    dest: "{{ wayland_path }}"
  register: wayland_repo
  notify: wayland-changed
  tags:
    - sway
    - git

- name: "Install dependency"
  apt:
    name:
      - libxml2-dev
      - graphviz
      - doxygen
      - xmlto
  become: True
  tags:
    - sway

- name: "wlroot dependencies"
  apt:
    name:
      - wayland-protocols
      - libwayland-dev
      - libegl1
      - libgles2
      - libglvnd-dev
      - libglvnd0
      - libgles2-mesa
      - libgles2-mesa-dev
      - libgbm1
      - libgbm-dev
      - libdrm2
      - libinput10
      - libinput-dev
      - libxkbcommon0
      - udev
      - libpixman-1-0
      - libcap2
      - libjson-c-dev
      - libx11-xcb-dev
      - libxcb-xinput-dev
      - libxcb-xinput0
      - libcap2
      - libcap-dev
      - libxcb-composite0
      - libxcb-composite0-dev
      - libxcb-dri3-dev
      - libxcb-present-dev
  become: True
  tags:
    - sway
  notify: wlroots-changed

- name: "Clone wlroots"
  git:
    repo: "https://github.com/swaywm/wlroots.git"
    dest: "{{ wlroots_path }}"
  notify: wlroots-changed
  tags:
    - sway
    - git

- name: "Clone sway"
  git:
    repo: "https://github.com/swaywm/sway.git"
    dest: "{{ sway_path }}"
  notify: sway-changed
  tags:
    - sway
    - git

- name: "Ensure session file is in place"
  copy:
    src: wayland-sessions/sway.desktop
    dest: /usr/share/wayland-sessions/sway.desktop
  become: True
  tags:
    - sway

- name: "Waybar dependencies"
  apt:
    name:
      - clang-tidy
      - gobject-introspection
      - libdbusmenu-gtk3-dev
      - libfmt-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libgtkmm-3.0-dev
      - libinput-dev
      - libjsoncpp-dev
      - libmpdclient-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libpulse-dev
      - libsigc++-2.0-dev
      - libspdlog-dev
      - scdoc
  become: True
  tags:
    - waybar
  notify:
    - waybar-changed

- name: "Clone Waybar"
  git:
    repo: "https://github.com/Alexays/Waybar"
    dest: "{{ waybar_path }}"
  tags:
    - waybar
  notify:
    - waybar-changed

- name: "Copy misc file"
  copy:
    src: "{{ waybar_path | expanduser }}/resources/custom_modules/mediaplayer.py"
    dest: "/usr/local/bin/mediaplayer.py"
    remote_src: yes
    mode: preserve
  become: True
  tags:
    - waybar

- name: "Clone swaylock"
  git:
    repo: "https://github.com/swaywm/swaylock"
    dest: "{{swaylock_path}}"
  tags:
    - wayland
  notify:
    - swaylock-changed

- name: "Clone swayidle"
  git:
    repo: "https://github.com/swaywm/swayidle"
    dest: "{{swayidle_path}}"
  tags:
    - wayland
  notify:
    - swayidle-changed

- meta: flush_handlers
