- name: "Install base chat applications"
  snap:
    name:
      - whatsdesk
  become: true

- name: "Install base chat applications"
  snap:
    name:
      - discord
    channel: beta
  become: true

- name: "Connect discord to system-observe"
  command: snap connect discord:system-observe
  become: True
  changed_when: false

- name: "Install slack"
  snap:
    name:
      - slack
    classic: yes
  become: true
