- name: "Install base chat applications"
  snap:
    name:
      - discord
      - whatsdesk
  become: true
  when: ansible_distribution == "Ubuntu"

- name: "Connect discord to system-observe"
  command: snap connect discord:system-observe
  become: True
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: "Install slack"
  snap:
    name:
      - slack
    classic: yes
  become: true
  when: ansible_distribution == "Ubuntu"
