- name: "Clone xcb-util-xrm"
  git:
    recursive: true
    track_submodules: yes
    repo: "https://www.github.com/Airblader/i3"
    dest: "{{directory.path}}/i3-gaps"
    version: gaps
  register: i3_gaps_git


- name: "Run autoreconf"
  command: autoreconf --force --install
  args:
    chdir: "{{directory.path}}/i3-gaps"

- name: "Remove build folder"
  file:
    path: "{{directory.path}}/i3-gaps/build"
    state: absent

- name: "Create build folder"
  file:
    path: "{{directory.path}}/i3-gaps/build"
    state: directory

- name: "Run configure"
  command: "{{directory.path}}/i3-gaps/configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers"
  args:
    chdir: "{{directory.path}}/i3-gaps/build"

- name: "Compile i3-gaps"
  make:
    chdir: "{{directory.path}}/i3-gaps/build"
    params:
      NUM_THREADS: 4

- name: "Install i3-gaps"
  make:
    chdir: "{{directory.path}}/i3-gaps/build"
    target: install
  become: true