- name: "Clone i3locks-fancy"
  git:
    recursive: true
    track_submodules: yes
    repo: "https://github.com/meskarune/i3lock-fancy.git"
    dest: "{{directory.path}}/i3lock-fancy"
  register: i3locks_fancy

- name: "Install i3locks-fancy"
  make:
    chdir: "{{directory.path}}/i3lock-fancy"
    target: install
  become: true
  when: i3locks_fancy.changed