- name: "Install i3-gaps dependent packages"
  apt:
    name:
      - libxcb1-dev
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - libxcb-shape0-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libev-dev
      - libxcb-cursor-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - autoconf
      - xutils-dev
      - libtool
      - automake
      - compton
      - libinput-tools
      - dunst
      - i3blocks
      - i3lock
      - i3status
      - maim
      - imagemagick
      - feh
      - dmenu

  become: true

- name: "Ensure base folder is created"
  file:
    path: "~/Code/Github"
    state: "directory"
  register: directory

- name: "Include xcb-util-xrm install"
  include_tasks:
    file: xcb_util_xrm.yml

- name: "Include i3-gaps install"
  include_tasks:
    file: i3_gaps.yml

- name: "Include i3locks-fancy install"
  include_tasks:
    file: i3locks_fancy.yml