- name: "Install mako dependencies"
  apt:
    name:
      - libcairo2-dev
      - libcairo2
      - libgdk-pixbuf2.0-0
      - cmake
      - python3-mako
      - pkg-config
      - libsystemd-dev
  become: True

- name: "Get Mako"
  git:
    repo: "https://github.com/emersion/mako.git"
    chdir: "{{ mako_directory }}"
  notify: mako-changed
