---

- name: "Ensure cache is updated"
  community.general.pacman:
    upgrade: yes
  become: True

- name: "Ensure sshpass is installed"
  community.general.pacman:
    name: sshpass
  become: True

- name: "Install snapd"
  aur:
    name:
      - snapd
  become: True
  become_user: aur_builder

- name: "Make sure snapd is enabled"
  systemd:
    name: snapd.service
    state: started
    enabled: True
  become: True

- name: "Ensure var folder"
  file:
    state: directory
    path: "/var/lib/devsible"
  become: True

- name: "Write current timestamp to file."
  copy:
    content: "{{ ansible_date_time.iso8601 }}"
    dest: /var/lib/devsible/last_run
  changed_when: False
  become: True

- name: Install iwd
  community.general.pacman:
    name: iwd
  become: True

- name: "Make sure iwd is enabled"
  systemd:
    name: iwd.service
    enabled: True
  become: True

- name: Make sure networkd is enabled
  systemd:
    name: systemd-networkd
    enabled: True
  become: True

- name: Make sure resolved is enabled
  systemd:
    name: systemd-resolved
    enabled: True
  become: True

- name: Copy network configuration
  copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/network/{{ item }}"
  with_items:
  - 10-wired.network
  - 11-wifi.network
  - 12-wlp.network
  become: True

- name: Copy iwd configuration
  copy:
    src: "files/iwd-main.conf"
    dest: /etc/iwd/main.conf
  become: True
