---

- name: "Include Ubuntu Tasks"
  include_tasks: "main_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- name: "Include Arch Tasks"
  include_tasks: "main_arch.yml"
  when: ansible_distribution == "Archlinux"
