---
- name: "Install package managers are present"
  apt:
    name:
      - aptitude
      - snapd
  become: true

- name: "Full dist-upgrade, long cache time"
  apt:
    upgrade: "dist"
    update_cache: "yes"
    autoremove: yes
    autoclean: yes
    cache_valid_time: 3600
  become: yes