---

- name: "Ensure cache is updated"
  community.general.pacman:
    upgrade: yes
  become: True

- name: "Ensure cache is updated"
  community.general.pacman:
    name: sshpass
  become: True

- name: "Ensure var folder"
  file:
    state: directory
    path: "/var/lib/devsible"
  become: True

- name: "Write current timestamp to file."
  copy:
    content: "{{ ansible_date_time.iso8601 }}"
    dest: /var/lib/devsible/last_run
  changed_when: False
  become: True

- user:
    name: aur_builder
    group: wheel
  become: True

- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: True

- name: Make sure a service is running
  systemd:
    name: systemd-networkd
    enabled: True
  become: True

- name: Make sure a service is running
  systemd:
    name: systemd-resolved
    enabled: True
  become: True
